  <script src="<?= base_url() ?>/assets/vendors/base/vendor.bundle.base.js"></script>
  <script src="<?= base_url() ?>/assets/vendors/chart.js/Chart.min.js"></script>
  <script src="<?= base_url() ?>/assets/vendors/datatables.net/jquery.dataTables.js"></script>
  <script src="<?= base_url() ?>/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
  <script src="<?= base_url() ?>/assets/js/off-canvas.js"></script>
  <script src="<?= base_url() ?>/assets/js/hoverable-collapse.js"></script>
  <script src="<?= base_url() ?>/assets/js/template.js"></script>
  <script src="<?= base_url() ?>/assets/js/dashboard.js"></script>
  <script src="<?= base_url() ?>/assets/js/data-table.js"></script>
  <script src="<?= base_url() ?>/assets/js/jquery.dataTables.js"></script>
  <script src="<?= base_url() ?>/assets/js/dataTables.bootstrap4.js"></script>